from aiohttp import ClientSession, client_exceptions, ClientError
from bs4 import BeautifulSoup
import asyncio
from .variant_1_creator.parser import get_parser, generate_data
from .variant_1_creator.generator import build_site_from_parser, build_site_from_data
from .variant_1_creator.helpers import identify_store, format_error_message
from .variant_1_creator.types import AppData
from typing import Optional, Literal
import random


async def fetch_html(session, url: str) -> str:
    """Fetch and return HTML from an App Store or Play Store URL with friendly error handling."""
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    }

    try:
        async with session.get(url, headers=headers) as resp:
            resp.raise_for_status()
            return await resp.text()

    except client_exceptions.InvalidURL:
        raise ValueError(
            f"The provided URL seems invalid: '{url}'. "
            f"Please ensure it includes 'https://' and points to an app store page."
        )

    except client_exceptions.ClientConnectorError:
        raise ConnectionError(
            f"Could not connect to '{url}'. Check your internet connection or verify that the store is reachable."
        )

    except client_exceptions.ClientResponseError as e:
        store = identify_store(url)
        msg = format_error_message(e.status, store)
        raise RuntimeError(f"Error fetching '{url}': {msg}")

    except Exception as e:
        raise RuntimeError(
            f"An unexpected error occurred while fetching '{url}': {str(e)}"
        )


async def build_from_app_data(app_data: AppData) -> str:
    """
    Build a site using pre-existing application data.
    """
    app_data["app_url"] = 'about:blank" target="_blank'
    return await build_site_from_data(app_data)


async def build_from_generated_data() -> str:
    """
    Generate new data and build a site from it.
    """
    data = await generate_data()
    return await build_site_from_data(data)


async def build_from_url(url: str) -> str:
    """
    Fetch HTML content from a URL and build a site from the parsed information.
    """
    async with ClientSession() as session:
        html = await fetch_html(session, url)
        parser = get_parser(url)
        soup = BeautifulSoup(html, "html.parser")
        data = parser(soup, url)

        if any(d is None for d in data.values()):
            raise ValueError(
                "Data has None values — parser couldn’t get data from link"
            )

        return await build_site_from_parser(data)


async def build_app_site(
    mode: Literal["app_data", "to_generate_data", "url"],
    app_data: Optional[AppData] = None,
    url: Optional[str] = None,
) -> str:
    match mode:
        case "app_data":
            if app_data:
                return await build_from_app_data(app_data)
            raise ValueError("In Data mode you need to put data")
        case "to_generate_data":
            return await build_from_generated_data()
        case "url":
            if url:
                return await build_from_url(url)
            raise ValueError("In URL mode you need to put url")
        case _:
            raise ValueError(f"Invalid build mode: {mode}")


if __name__ == "__main__":
    app_demo = AppData(
        title="DemoApp",
        description="This is a sample app used for testing the AppData schema.",
        icon_data="iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANIElEQVR4nOzXjdfXdX3Hca95TVEUkbzZslRsYta0wnIau7zJsGOKTUTFhG42I3PZWqbT5dBFG6t5lC1t2dFs3uGWaAfdvEnc2oRGSZidNigYCAIhKAgh4oD2V7zO6ZzX4/EHvD7f84Nzntd7cODkNXskXbJlUnR/7usLo/uHTRse3d/1ldOi+4/91Xuj+5cef3l0/8prt0T3f3uvc6L7n5kwPbq/9y3zo/tvmT4juv/VUx6N7p970pjo/jX73xzdf+OnNkf3fyO6DsCvLQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUGrgI4sujz5wzs2vRfevuO/M6P7mzz4U3T/1t0ZG92/9+8nR/bl3LYvuD/z8/uj+lf80K7o/csr06P7Qc+Oi+wvvPzK6v2jFpuj+kheHR/cX/fG90f0PzfqD6L4LAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoNTA4aSD6wO4pY6L7D4/5QHR/+5Oro/uvb/i36P7mS56O7j836azo/t2T5kT3h87/eXR//ZKJ0f2rli+P7r//tpHR/THHHR/df+7yF6P728d/Jbr/2MTs97sAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSA19cPDf6wOol34zu37Pg2ej+nPFLovuvTP12dP/xVUuj+5O3vhzd/71PTI3uv/O17PePPeJfo/sfWvZSdP/Nh94e3Z+89Oro/pNn7B/df8fJ06L7J6z7QHTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBr82OHfiz6wckR2/5Xz94nuj975vuj+S0/siu7/5lWnRfcX3T47ur/tuPOj+zNu2h7dX3P+8Oj+hHvHRvffsO7R6P7pY+6L7v/4LROi++97Jvs39IbPPBvddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGV3/5V9EHZh62Pbp/8CMnRPd3PnVXdH/t2aOj+z98297R/dGPXRbdv//bfxjdX3XBzOj+/x68Mbp/8dFfiu4v+emPo/v3HjEtuv/geR+N7t/43fdE94/da3l03wUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQaOPHhadEHnv+b+dH9Cx+eF92fdd+o6P4ee30sOj+0759F96eM/np0/7TpO6P7e9/6eHR/1IcPju7feO7G6P4P/va/o/snXLtPdH/Ruz8X3R/7TPbf99Hr50b3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKnBy0bsjj7w0y0fjO4/tuMfo/vXnjUxuj/uO9nfZ8emWdH9dQdkv/+td8yM7q/55Y7o/m0PHBTdf9cnb4juH3HgvOj+sM/tiu4fu+6F6P4NBy6I7k9a//3ovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACg1eNKwS6MP7Psfl0X3dz3xQHR/85+ujO7/avr06P5B3xqM7j+7eH10f/iwFdH9M3/ne9H9mcOGovuPr3w+uv+uTx8R3f/qz7ZH90fs+ano/hm3XhXdH37dKdF9FwBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUGrgpjVbow8ccvRfRPdXDP9ldH/Ze++O7t+8/0XR/QfPfCq6f82Rfx3df+NFR0X3737Du6P710z4YnR/1Mi3RvefOPKA6P6860dG9/99j+z3v773xOj+PXt+I7rvAgAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg1ue3hT9IF7lp0Q3R99yyXR/Rln/3l0/9BDpkX3fzD1zuj+Bf+8Mrr/pbNmRfeH/ucL0f1zXz4zuj/jJ09G9xe+9vvR/Rv/5Nbo/tnf2je6/6ZvbIzu33TMnOi+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDU47Bfzow/MnnpddH/UFVdF9z9y9enR/acf2B3d37bqvOj+tB9dGt1/6OJjovvHzTk0un/H5MHo/tgTfxHdHz/03ej+vE9Pie6/7Yml0f2vjVsc3f+XGf8X3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBq7bujv6wJ1vXxrdv+/986L7+338jOj+OfPWRfc/uHV1dP9Hc7K/z5ZHvhbdH7Pj1ej+oRPuje7/56MvRfcPuf6H0f1TF2X3N86+Irp/way7o/sbF2b/f7oAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSg/uvXR59YMXstdH9yUd9Prp/8rot0f0Rdx4W3b9l4oro/ieP3h3dP2bxzuj+kfNmRfd/8g/nRPcXfP2p6P6k0++M7h/0yDui+1dv+350f+zHb4vuL9l4VHTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBp46J23Rx9YvGG/6P7bJ30+un/ql0+J7r/wzRej+1+Ycld0f+YpQ9H92ReeFN3f9Lufje5/Z9yq6P6UBXdE9x8c8Wp0f3DDtuj+Mxd/NLq/59zzovvHTl0f3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBq+c/+boAz97/uLo/n89fmF0/6IL3xPdf/rvbojuH7/fXtH9Vz6xI7p/7YIPR/fHD70pun/4H42K7r98+YHR/bXj7onuH37Nguj++L/cJ7q/6cSLovsHvPpCdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACU+v8AAAD///pBiBdt4hEvAAAAAElFTkSuQmCC",
        screenshots_data=[
            "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANGUlEQVR4nOzXjdfXdX3Hccmf5dJ2qWgSKsObFK9S0zk1bA3dOqMcYWFidFDQ2dEpaHnK3CxrYt5k2vJ03NqCOiYBbh6gA0wD3cGchLjiFEUIF8sciLuo2aEa1W7+itc5nfN6PP6A1+d3fud8z/O8B1MvGzog6ejlM6P72y86O7r/uys/Fd3/6v5vRPdXfGtfdH/CH06M7k/94zXR/Su3zYruX3LFMdH9Vauuj+4PjZ0R3X/Ljp3R/Um7D4/uH/7u86L7yxcvju6/KroOwG8tAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQanDGwnnRB5a8+Jro/ptevCG6/x/Lvxjdv+Ggz2X3Xzw5ur93w7ro/nOPnhXd3/SDZ6L7T/7r66L7a8+/Irr/+eG/j+7fvvTe6P70x38a3T/81tnR/V0bt0T3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKnBEee8J/rAxImfiO5P/vDl0f2N8+6J7t88fU90/7FLR6P75/zi+ej+tktWRfdX/HN0/oDhL98S3b/8HVOi+0Oja6P73/1Idv+8/83uLxj5z+j+5U9nv18XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQanDh+0+NPrDtw1uj+z//6FHR/ZG1b4/uH7/4XdH9DRNXRvd33/h70f1dZ/8qun/Sax+J7h999bzo/ooX9kX3D737vuj+DSM7ovs3br8lun/zY09E96+Y9F/RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqzAvXXxt94G/WfzW6f+u39kb3nz7m8ej+lw75TnR/5pRXovvHDR0S3f+XLaPR/dVzNkb3x78q+/9sPG11dP/lddnva/3WN0b3h++8Orq/5Iw/j+4fNX9XdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGjPryDXRB05fsye6f/hhF0f33/TmE6L7l15zbnT/Oy8cHN2fcfKc6P6Phr4d3V/6lRXR/Z3LfxrdHzt/S3T/6guvj+7vfF/2/zn4pWnR/Umzj4/u3zH87ui+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDV4ZPkr0Qe2jpkR3f/FkpXR/c3Hjo/uH//v34juP7f0jOj+pi1/Ed2f/eD/Rfc/uHZqdH/ptDXR/Sen/ji6/5ovnRDdf/znP4vun/6TS6L7996wIrr/wOBj0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQavDRcZOiD9z6D7dE9x9aOCG6f/HrFkb39x/y19H9K549K7r/mX0j0f0Hjrw9un/bw6+O7g+dvTe6f9yxF0f3n314dXT/hw/Mj+7PX5/9vsZ89rTo/kFrPxvddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGe27+evSByYceHd3fv2pBdP+UdT+L7l91wqLo/ty5F0f3p7/1lOj+hgvfH93/+If2RvfHf3JmdH/zO6+J7q8ae1d2/82bo/sXHPjp6P6dp4yL7o+snhXddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGuyceFX3grPfeFd3/2udPie7vuebR6P5vrvyT6P70h2ZG96ce+D/R/fmLl0X3F117XXR/zLUHRfefGD0zun/OBeui+w/teCa6v3ncVdH9BUPZ33/mgt3RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqcOZPtkYfWPz6a6P7C2bdFN2/4OZBdP/uLzwV3V/2yZXR/U8/PRrdv23BSdH9xfe9Orp/xLg50f3xG/80ur9/2Yei+0t+Mzu6f+W256L7u18+Irp/y7wDo/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1Jiz52Uf+LcZG6L7q/e8K7o/et+e6P7VO/4uuj/6vvHR/R3zTo3uzzlye3T/qQPmRvcves/D0f0prx+J7t9/6Fui+4MfvTe6P/lTi6L7v3PvF6L7f/CG0ei+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDXmtrcPRx84efNF0f2vv20kuv+Rz3wsuj9n+onR/WNuPz+6/+Pzr4ruP/vkwuj+906cGt2fPPGfovtjt18X3V977LTo/l8tHoruf2/WqdH9OXu/G92ftm9ZdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGvz6nndGH/ijXfdH959/aiS6/4MH50f3X7thbnT/scPuiO6PvXFbdP+mwz4X3f/vCROi+9OmjI3uXzju+Oj+zuGjovuPXPeP0f2vzP51dP8d55wa3b/slx+P7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSg5e+vSn6wOl/md1fdtWD0f1Ddr0tur/im8uj+9NnvzG6P5g5I7p/xysnRfeXvLQ7uv/9Q6dF9yecdU90/4MfWBXdX/Nnb4ju33ru89H9Sz9wXnR/35JF0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQarBlxeToAyf/7Vuj+7/81f3R/W9+/9Ho/rY9U6L7J+67K7p/7vDc6P5p6w+O7g/vfia6//Lar0X3j3viguj+CV/cFN3/8ifujO7//v13R/fn3HRMdH/SZT+M7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBS/x8AAP//OjV9Cbcm5NsAAAAASUVORK5CYII=",
            "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANGUlEQVR4nOzXjdfXdX3Hccmf5dJ2qWgSKsObFK9S0zk1bA3dOqMcYWFidFDQ2dEpaHnK3CxrYt5k2vJ03NqCOiYBbh6gA0wD3cGchLjiFEUIF8sciLuo2aEa1W7+itc5nfN6PP6A1+d3fud8z/O8B1MvGzog6ejlM6P72y86O7r/uys/Fd3/6v5vRPdXfGtfdH/CH06M7k/94zXR/Su3zYruX3LFMdH9Vauuj+4PjZ0R3X/Ljp3R/Um7D4/uH/7u86L7yxcvju6/KroOwG8tAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQanDGwnnRB5a8+Jro/ptevCG6/x/Lvxjdv+Ggz2X3Xzw5ur93w7ro/nOPnhXd3/SDZ6L7T/7r66L7a8+/Irr/+eG/j+7fvvTe6P70x38a3T/81tnR/V0bt0T3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKnBEee8J/rAxImfiO5P/vDl0f2N8+6J7t88fU90/7FLR6P75/zi+ej+tktWRfdX/HN0/oDhL98S3b/8HVOi+0Oja6P73/1Idv+8/83uLxj5z+j+5U9nv18XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQanDh+0+NPrDtw1uj+z//6FHR/ZG1b4/uH7/4XdH9DRNXRvd33/h70f1dZ/8qun/Sax+J7h999bzo/ooX9kX3D737vuj+DSM7ovs3br8lun/zY09E96+Y9F/RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqzAvXXxt94G/WfzW6f+u39kb3nz7m8ej+lw75TnR/5pRXovvHDR0S3f+XLaPR/dVzNkb3x78q+/9sPG11dP/lddnva/3WN0b3h++8Orq/5Iw/j+4fNX9XdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGjPryDXRB05fsye6f/hhF0f33/TmE6L7l15zbnT/Oy8cHN2fcfKc6P6Phr4d3V/6lRXR/Z3LfxrdHzt/S3T/6guvj+7vfF/2/zn4pWnR/Umzj4/u3zH87ui+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDV4ZPkr0Qe2jpkR3f/FkpXR/c3Hjo/uH//v34juP7f0jOj+pi1/Ed2f/eD/Rfc/uHZqdH/ptDXR/Sen/ji6/5ovnRDdf/znP4vun/6TS6L7996wIrr/wOBj0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQavDRcZOiD9z6D7dE9x9aOCG6f/HrFkb39x/y19H9K549K7r/mX0j0f0Hjrw9un/bw6+O7g+dvTe6f9yxF0f3n314dXT/hw/Mj+7PX5/9vsZ89rTo/kFrPxvddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGe27+evSByYceHd3fv2pBdP+UdT+L7l91wqLo/ty5F0f3p7/1lOj+hgvfH93/+If2RvfHf3JmdH/zO6+J7q8ae1d2/82bo/sXHPjp6P6dp4yL7o+snhXddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGuyceFX3grPfeFd3/2udPie7vuebR6P5vrvyT6P70h2ZG96ce+D/R/fmLl0X3F117XXR/zLUHRfefGD0zun/OBeui+w/teCa6v3ncVdH9BUPZ33/mgt3RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqcOZPtkYfWPz6a6P7C2bdFN2/4OZBdP/uLzwV3V/2yZXR/U8/PRrdv23BSdH9xfe9Orp/xLg50f3xG/80ur9/2Yei+0t+Mzu6f+W256L7u18+Irp/y7wDo/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1Jiz52Uf+LcZG6L7q/e8K7o/et+e6P7VO/4uuj/6vvHR/R3zTo3uzzlye3T/qQPmRvcves/D0f0prx+J7t9/6Fui+4MfvTe6P/lTi6L7v3PvF6L7f/CG0ei+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDXmtrcPRx84efNF0f2vv20kuv+Rz3wsuj9n+onR/WNuPz+6/+Pzr4ruP/vkwuj+906cGt2fPPGfovtjt18X3V977LTo/l8tHoruf2/WqdH9OXu/G92ftm9ZdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGvz6nndGH/ijXfdH959/aiS6/4MH50f3X7thbnT/scPuiO6PvXFbdP+mwz4X3f/vCROi+9OmjI3uXzju+Oj+zuGjovuPXPeP0f2vzP51dP8d55wa3b/slx+P7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSg5e+vSn6wOl/md1fdtWD0f1Ddr0tur/im8uj+9NnvzG6P5g5I7p/xysnRfeXvLQ7uv/9Q6dF9yecdU90/4MfWBXdX/Nnb4ju33ru89H9Sz9wXnR/35JF0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQarBlxeToAyf/7Vuj+7/81f3R/W9+/9Ho/rY9U6L7J+67K7p/7vDc6P5p6w+O7g/vfia6//Lar0X3j3viguj+CV/cFN3/8ifujO7//v13R/fn3HRMdH/SZT+M7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBS/x8AAP//OjV9Cbcm5NsAAAAASUVORK5CYII=",
            "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANGUlEQVR4nOzXjdfXdX3Hccmf5dJ2qWgSKsObFK9S0zk1bA3dOqMcYWFidFDQ2dEpaHnK3CxrYt5k2vJ03NqCOiYBbh6gA0wD3cGchLjiFEUIF8sciLuo2aEa1W7+itc5nfN6PP6A1+d3fud8z/O8B1MvGzog6ejlM6P72y86O7r/uys/Fd3/6v5vRPdXfGtfdH/CH06M7k/94zXR/Su3zYruX3LFMdH9Vauuj+4PjZ0R3X/Ljp3R/Um7D4/uH/7u86L7yxcvju6/KroOwG8tAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQanDGwnnRB5a8+Jro/ptevCG6/x/Lvxjdv+Ggz2X3Xzw5ur93w7ro/nOPnhXd3/SDZ6L7T/7r66L7a8+/Irr/+eG/j+7fvvTe6P70x38a3T/81tnR/V0bt0T3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKnBEee8J/rAxImfiO5P/vDl0f2N8+6J7t88fU90/7FLR6P75/zi+ej+tktWRfdX/HN0/oDhL98S3b/8HVOi+0Oja6P73/1Idv+8/83uLxj5z+j+5U9nv18XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQanDh+0+NPrDtw1uj+z//6FHR/ZG1b4/uH7/4XdH9DRNXRvd33/h70f1dZ/8qun/Sax+J7h999bzo/ooX9kX3D737vuj+DSM7ovs3br8lun/zY09E96+Y9F/RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqzAvXXxt94G/WfzW6f+u39kb3nz7m8ej+lw75TnR/5pRXovvHDR0S3f+XLaPR/dVzNkb3x78q+/9sPG11dP/lddnva/3WN0b3h++8Orq/5Iw/j+4fNX9XdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGjPryDXRB05fsye6f/hhF0f33/TmE6L7l15zbnT/Oy8cHN2fcfKc6P6Phr4d3V/6lRXR/Z3LfxrdHzt/S3T/6guvj+7vfF/2/zn4pWnR/Umzj4/u3zH87ui+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDV4ZPkr0Qe2jpkR3f/FkpXR/c3Hjo/uH//v34juP7f0jOj+pi1/Ed2f/eD/Rfc/uHZqdH/ptDXR/Sen/ji6/5ovnRDdf/znP4vun/6TS6L7996wIrr/wOBj0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQavDRcZOiD9z6D7dE9x9aOCG6f/HrFkb39x/y19H9K549K7r/mX0j0f0Hjrw9un/bw6+O7g+dvTe6f9yxF0f3n314dXT/hw/Mj+7PX5/9vsZ89rTo/kFrPxvddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGe27+evSByYceHd3fv2pBdP+UdT+L7l91wqLo/ty5F0f3p7/1lOj+hgvfH93/+If2RvfHf3JmdH/zO6+J7q8ae1d2/82bo/sXHPjp6P6dp4yL7o+snhXddwEAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUGuyceFX3grPfeFd3/2udPie7vuebR6P5vrvyT6P70h2ZG96ce+D/R/fmLl0X3F117XXR/zLUHRfefGD0zun/OBeui+w/teCa6v3ncVdH9BUPZ33/mgt3RfRcAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBqcOZPtkYfWPz6a6P7C2bdFN2/4OZBdP/uLzwV3V/2yZXR/U8/PRrdv23BSdH9xfe9Orp/xLg50f3xG/80ur9/2Yei+0t+Mzu6f+W256L7u18+Irp/y7wDo/suAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACg1Jiz52Uf+LcZG6L7q/e8K7o/et+e6P7VO/4uuj/6vvHR/R3zTo3uzzlye3T/qQPmRvcves/D0f0prx+J7t9/6Fui+4MfvTe6P/lTi6L7v3PvF6L7f/CG0ei+CwCglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKDXmtrcPRx84efNF0f2vv20kuv+Rz3wsuj9n+onR/WNuPz+6/+Pzr4ruP/vkwuj+906cGt2fPPGfovtjt18X3V977LTo/l8tHoruf2/WqdH9OXu/G92ftm9ZdN8FAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUGvz6nndGH/ijXfdH959/aiS6/4MH50f3X7thbnT/scPuiO6PvXFbdP+mwz4X3f/vCROi+9OmjI3uXzju+Oj+zuGjovuPXPeP0f2vzP51dP8d55wa3b/slx+P7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSg5e+vSn6wOl/md1fdtWD0f1Ddr0tur/im8uj+9NnvzG6P5g5I7p/xysnRfeXvLQ7uv/9Q6dF9yecdU90/4MfWBXdX/Nnb4ju33ru89H9Sz9wXnR/35JF0X0XAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQarBlxeToAyf/7Vuj+7/81f3R/W9+/9Ho/rY9U6L7J+67K7p/7vDc6P5p6w+O7g/vfia6//Lar0X3j3viguj+CV/cFN3/8ifujO7//v13R/fn3HRMdH/SZT+M7rsAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBS/x8AAP//OjV9Cbcm5NsAAAAASUVORK5CYII=",
        ],
    )
    app_urls = [
        "https://itunes.apple.com/ua/app/chatgpt/id6448311069",
        "https://apps.apple.com/ua/app/superhuman-mail/id1120837655",
        "https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact&pcampaignid=merch_published_cluster_promotion_battlestar_featured_games",
        "https://play.google.com/store/apps/details?id=ua.slando",
        "https://market.android.com/details?id=com.google.earth",
        "https://play.google.com/store/apps/details?id=com.kakaogames.gbod&pcampaignid=merch_published_cluster_promotion_battlestar_featured_games",
        "https://play.google.com/store/apps/details?id=com.kakaogames.eversoul",
    ]

    app_url = random.choice(app_urls)

    abs_path = asyncio.run(build_app_site(mode="url", app_data=app_demo, url=app_url))
    print(abs_path)
